name: Setup
description: Environment setup

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@739bfe42ca9233c5e6aca07c1a25a9d34aca49b0 # v6

    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version-file: package.json
        cache: pnpm

    - shell: bash
      run: |
        pnpm install --frozen-lockfile
